// GENERATED by orbs/tools/codegen-kotlin.ts from spec/orbs-spec.json — do not edit.
// spec 1.0.0 · thinking-orbs 0.3.1

package com.jakubantalik.thinkingorbs

/** Which animation to show. [label] matches the web component's aria-label. */
enum class OrbState(val id: String, val label: String) {
    Working("working", "Working…"),
    Searching("searching", "Searching…"),
    Solving("solving", "Solving…"),
    Listening("listening", "Listening…"),
    Connecting("connecting", "Connecting…"),
    Weaving("weaving", "Weaving…"),
    Composing("composing", "Composing…"),
    Breathing("breathing", "Thinking…"),
    Shaping("shaping", "Shaping…"),
    ;

    internal val mode: OrbMode
        get() = when (this) {
            Working -> OrbMode.Orbits
            Searching -> OrbMode.Globe
            Solving -> OrbMode.Rubik
            Listening -> OrbMode.Wave
            Connecting -> OrbMode.Web
            Weaving -> OrbMode.Braid
            Composing -> OrbMode.Ribbon
            Breathing -> OrbMode.Ring
            Shaping -> OrbMode.Morph
        }

    companion object {
        fun fromId(id: String): OrbState? = entries.firstOrNull { it.id == id }
    }
}

/**
 * Rendered size in points. Exactly two tuned presets ship — they are separate
 * designs, each with its own dot count and speed, not a scale factor.
 */
enum class OrbSize(val px: Int) {
    Px64(64),
    Px20(20),
    ;

    val value: Double get() = px.toDouble()

    companion object {
        fun fromPx(px: Int): OrbSize? = entries.firstOrNull { it.px == px }
    }
}

internal enum class OrbMode(val id: String) {
    Orbits("orbits"),
    Globe("globe"),
    Rubik("rubik"),
    Wave("wave"),
    Web("web"),
    Braid("braid"),
    Ribbon("ribbon"),
    Ring("ring"),
    Morph("morph"),
}

internal object OrbSpec {

    class Preset(
        @JvmField val speed: Double,
        @JvmField val count: Double,
        @JvmField val size: Double,
        @JvmField val extra: Map<String, Double>,
    )

    /** Per-mode density/geometry before any preset multiplier. */
    val baseProfiles: Map<OrbMode, Map<String, Double>> = mapOf(
        OrbMode.Orbits to mapOf("orbitN" to 12.0, "ghostN" to 40.0, "ghostR" to 0.9, "ghostA" to 0.5, "particles" to 3.0, "partR" to 1.2, "partRDepth" to 1.6, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Globe to mapOf("latRings" to 17.0, "lonDensity" to 44.0, "rBase" to 0.6, "rDepth" to 1.7, "rBoost" to 1.0, "inkFar" to 0.62, "inkSpan" to 0.54, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Rubik to mapOf("latRings" to 15.0, "lonDensity" to 40.0, "moveCount" to 14.0, "rBase" to 0.6, "rDepth" to 1.7, "rActive" to 0.3, "inkFar" to 0.62, "inkSpan" to 0.54, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Wave to mapOf("rings" to 15.0, "lonDensity" to 40.0, "rBase" to 0.6, "rDepth" to 1.7, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Web to mapOf("nodeN" to 30.0, "thr" to 0.72, "signals" to 5.0, "nodeR" to 1.4, "nodeRDepth" to 1.8, "lineW" to 0.8, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Braid to mapOf("strandN" to 52.0, "turns" to 3.0, "ghostN" to 150.0, "rBase" to 1.2, "rDepth" to 1.8, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Ribbon to mapOf("lanes" to 5.0, "segs" to 88.0, "ghostN" to 150.0, "rBase" to 1.1, "rDepth" to 1.7, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Ring to mapOf("lanes" to 5.0, "segs" to 88.0, "ghostN" to 0.0, "faceOn" to 1.0, "rBase" to 1.1, "rDepth" to 1.7, "rsPow" to 0.6, "rMin" to 0.3),
        OrbMode.Morph to mapOf("rDot" to 0.021, "iconD" to 1.0, "rMin" to 0.25),
    )

    /** Per (mode x size) baked tuning. */
    val presets: Map<OrbMode, Map<OrbSize, Preset>> = mapOf(
        OrbMode.Orbits to mapOf(
            OrbSize.Px64 to Preset(1.885, 1.0, 1.0, emptyMap()),
            OrbSize.Px20 to Preset(3.9, 0.238, 2.4, emptyMap()),
        ),
        OrbMode.Globe to mapOf(
            OrbSize.Px64 to Preset(2.015, 0.42, 1.15, mapOf("scanMul" to 4.08, "dimBase" to 0.45)),
            OrbSize.Px20 to Preset(2.665, 0.105, 1.75, mapOf("scanMul" to 4.335, "dimBase" to 0.45)),
        ),
        OrbMode.Rubik to mapOf(
            OrbSize.Px64 to Preset(1.82, 0.35, 1.05, emptyMap()),
            OrbSize.Px20 to Preset(1.95, 0.088, 1.9, emptyMap()),
        ),
        OrbMode.Wave to mapOf(
            OrbSize.Px64 to Preset(4.388, 0.341, 1.0, emptyMap()),
            OrbSize.Px20 to Preset(3.998, 0.105, 1.6, emptyMap()),
        ),
        OrbMode.Web to mapOf(
            OrbSize.Px64 to Preset(3.315, 1.35, 0.95, emptyMap()),
            OrbSize.Px20 to Preset(6.63, 0.25, 1.52, emptyMap()),
        ),
        OrbMode.Braid to mapOf(
            OrbSize.Px64 to Preset(1.625, 0.5, 1.0, emptyMap()),
            OrbSize.Px20 to Preset(2.75, 0.1125, 1.36, emptyMap()),
        ),
        OrbMode.Ribbon to mapOf(
            OrbSize.Px64 to Preset(2.34, 0.25, 0.85, mapOf("spin" to 0.0, "bandMul" to 3.9, "wobMul" to 1.0)),
            OrbSize.Px20 to Preset(3.12, 0.051, 1.073, mapOf("spin" to 0.0, "bandMul" to 4.94, "wobMul" to 1.0)),
        ),
        OrbMode.Ring to mapOf(
            OrbSize.Px64 to Preset(3.24, 0.25, 0.956, mapOf("spin" to 0.0, "bandMul" to 3.627, "wobMul" to 0.368)),
            OrbSize.Px20 to Preset(3.78, 0.028, 1.622, mapOf("spin" to 0.0, "bandMul" to 3.968, "wobMul" to 0.565)),
        ),
        OrbMode.Morph to mapOf(
            OrbSize.Px64 to Preset(2.405, 0.702, 0.395, mapOf("spread" to 1.45)),
            OrbSize.Px20 to Preset(2.08, 0.53, 1.011, mapOf("spread" to 1.45)),
        ),
    )

    /** 2-D lattices scale by sqrt(count) on each axis so the TOTAL scales by count. */
    val countPairs: List<Pair<String, String>> = listOf(
        "latRings" to "lonDensity",
        "rings" to "lonDensity",
        "lanes" to "segs",
    )
    val countKeys: List<String> = listOf("orbitN", "ghostN", "nodeN", "strandN", "signals")
    val iconDensityKeys: List<String> = listOf("iconD")
    val radiusKeys: List<String> = listOf("rBase", "rDepth", "rActive", "rDot", "ghostR", "partR", "partRDepth", "nodeR", "nodeRDepth")

    /** The static frame reduced-motion users see. */
    const val REDUCED_MOTION_T: Double = 0.6
}
