// Generates orbs/src/main/kotlin/com/jakubantalik/thinkingorbs/OrbSpec.kt
// from the upstream spec/orbs-spec.json.
//
// The Kotlin port hand-transcribes the MATH (that is what the golden tests
// guard) but never the TUNINGS. Those are generated, so a retune upstream
// flows here by re-running this script instead of retyping forty literals.
//
// Run:  npx tsx orbs/tools/codegen-kotlin.ts <path-to-thinking-orbs>

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const pkg = process.argv[2];
if (!pkg) {
  console.error('usage: tsx codegen-kotlin.ts <path-to-thinking-orbs-package>');
  process.exit(1);
}
const spec = JSON.parse(readFileSync(resolve(pkg, 'spec/orbs-spec.json'), 'utf8'));

const pascal = (s: string) => s[0].toUpperCase() + s.slice(1);

// Kotlin, unlike Swift, does not widen a bare Int literal (e.g. `12`, `1`, `0`)
// to Double at a Double-typed call site — it is a compile error. Every numeric
// literal we emit into a Double position must carry an explicit fractional
// part. But a completed exponent form (`1e+21`) cannot take a trailing `.0` —
// Kotlin's literal grammar rejects it — and is already a valid Double literal
// on its own, so leave those alone.
const num = (n: number) =>
  Number.isInteger(n) && !String(n).includes('e') ? `${n}.0` : String(n);

// Kotlin string literals: backslash and quote need escaping, and `$` starts a
// string template (Swift's \(...) interpolation has no equivalent hazard,
// which is why codegen-swift.ts needs none of this). Every spec-derived
// string — labels, map keys, state/mode ids, scaling key names — must be
// routed through this before interpolation. Escape backslash FIRST or the
// backslashes just added for `"` and `$` get double-escaped.
const kstr = (s: string) =>
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$');

// Every per-key spec lookup must fail loudly and by name, not by silently
// emitting the string "undefined" into the generated file (labels) or
// throwing a generic TypeError three calls away from the actual missing key
// (stateToMode / baseProfiles / presets).
function must<T>(value: T | undefined, what: string): T {
  if (value === undefined) throw new Error(`orbs-spec.json is missing ${what}`);
  return value;
}

const optsLiteral = (o: Record<string, number>) =>
  o && Object.keys(o).length
    ? `mapOf(${Object.entries(o).map(([k, v]) => `"${kstr(k)}" to ${num(v)}`).join(', ')})`
    : 'emptyMap()';

const states = spec.enums.states as string[];
const modes = spec.enums.modes as string[];

const out = `// GENERATED by orbs/tools/codegen-kotlin.ts from spec/orbs-spec.json — do not edit.
// spec ${spec.specVersion} · thinking-orbs ${spec.sourceLibrary.version}

package com.jakubantalik.thinkingorbs

/** Which animation to show. [label] matches the web component's aria-label. */
enum class OrbState(val id: String, val label: String) {
${states.map((s) => `    ${pascal(s)}("${kstr(s)}", "${kstr(must(spec.labels[s], `labels.${s}`))}"),`).join('\n')}
    ;

    internal val mode: OrbMode
        get() = when (this) {
${states.map((s) => `            ${pascal(s)} -> OrbMode.${pascal(must(spec.stateToMode[s], `stateToMode.${s}`))}`).join('\n')}
        }

    companion object {
        fun fromId(id: String): OrbState? = entries.firstOrNull { it.id == id }
    }
}

/**
 * Rendered size in points. Exactly two tuned presets ship — they are separate
 * designs, each with its own dot count and speed, not a scale factor.
 */
enum class OrbSize(val px: Int) {
    Px64(64),
    Px20(20),
    ;

    val value: Double get() = px.toDouble()

    companion object {
        fun fromPx(px: Int): OrbSize? = entries.firstOrNull { it.px == px }
    }
}

internal enum class OrbMode(val id: String) {
${modes.map((m) => `    ${pascal(m)}("${kstr(m)}"),`).join('\n')}
}

internal object OrbSpec {

    class Preset(
        @JvmField val speed: Double,
        @JvmField val count: Double,
        @JvmField val size: Double,
        @JvmField val extra: Map<String, Double>,
    )

    /** Per-mode density/geometry before any preset multiplier. */
    val baseProfiles: Map<OrbMode, Map<String, Double>> = mapOf(
${modes.map((m) => `        OrbMode.${pascal(m)} to ${optsLiteral(must(spec.baseProfiles[m], `baseProfiles.${m}`))},`).join('\n')}
    )

    /** Per (mode x size) baked tuning. */
    val presets: Map<OrbMode, Map<OrbSize, Preset>> = mapOf(
${modes
  .map((m) => {
    const rows = (['64', '20'] as const)
      .map((sz) => {
        const p = must(spec.presets[m]?.[sz], `presets.${m}.${sz}`);
        return `            OrbSize.Px${sz} to Preset(${num(p.speed)}, ${num(p.count)}, ${num(p.size)}, ${optsLiteral(p.extra)}),`;
      })
      .join('\n');
    return `        OrbMode.${pascal(m)} to mapOf(\n${rows}\n        ),`;
  })
  .join('\n')}
    )

    /** 2-D lattices scale by sqrt(count) on each axis so the TOTAL scales by count. */
    val countPairs: List<Pair<String, String>> = listOf(
${spec.scaling.countPairs.map(([a, b]: [string, string]) => `        "${kstr(a)}" to "${kstr(b)}",`).join('\n')}
    )
    val countKeys: List<String> = listOf(${spec.scaling.countKeys.map((k: string) => `"${kstr(k)}"`).join(', ')})
    val iconDensityKeys: List<String> = listOf(${spec.scaling.iconDensityKeys.map((k: string) => `"${kstr(k)}"`).join(', ')})
    val radiusKeys: List<String> = listOf(${spec.scaling.radiusKeys.map((k: string) => `"${kstr(k)}"`).join(', ')})

    /** The static frame reduced-motion users see. */
    const val REDUCED_MOTION_T: Double = 0.6
}
`;

const dest = resolve(__dirname, '../src/main/kotlin/com/jakubantalik/thinkingorbs/OrbSpec.kt');
writeFileSync(dest, out);
console.log(`OrbSpec.kt — ${states.length} states, ${modes.length} modes (spec ${spec.specVersion})`);
